;GARY

    db RIVAL1, 1 ; Oak's Lab - 5, EEVEE, 0
    ; 5, EEVEE
    db 1, 1, TACKLE ; LV 1
    db 1, 2, TAIL_WHIP ; LV 1
    
    db 0  ; Finaliza a lista

;-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
;-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
;-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

    db RIVAL1, 2 ; Route 22 - 9, SPEAROW, 9, MANKEY, 8, EEVEE, 0
    ; 9, SPEAROW
    db 1, 1, PECK ; LV 1
    db 1, 2, GROWL ; LV 1
    db 1, 3, LEER ; LV 9

    ; 9, MANKEY
    db 2, 1, LOW_KICK ; LV 9
    db 2, 2, SCRATCH ; LV 1
    db 2, 3, LEER ; LV 1

    ; 8, EEVEE
    db 3, 1, TACKLE ; LV 1
    db 3, 2, TAIL_WHIP ; LV 1
    db 3, 3, SAND_ATTACK ; LV 8

    db 0  ; Finaliza a lista

;-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
;-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
;-------------------------------------------------------------------------------------------------------------------------------------------------------------------------

    db RIVAL1, 3 ; Cerulean City - 17, SPEAROW, 18, MANKEY, 15, SANDSHREW, 15, RATTATA, 17, EEVEE, 0
    ; 18, SPEAROW
    db 1, 1, PECK ; LV 1
    db 1, 2, RAZOR_WIND ; TM 02 NÃO SEI QUANTAS TEM NO JOGO 
    db 1, 3, LEER ; LV 9
    db 1, 4, GROWL ; LV 1

    ; 18, MANKEY
    db 2, 1, LOW_KICK ; LV 9
    db 2, 2, KARATE_CHOP ; LV 15
    db 2, 3, SCRATCH ; LV 1
    db 2, 4, LEER ; LV 1        

    ; 15, SANDSHREW
    db 3, 1, SCRATCH ; LV 1
    db 3, 2, BIDE ; TM 34 SÓ TEM UM NO JOGO
    db 3, 3, SEISMIC_TOSS ; TEM DUAS NO JOGO
    db 3, 3, SAND_ATTACK ; LV 10

    ; 15, RATTATA
    db 4, 1, HYPER_FANG ; LV 14
    db 4, 2, QUICK_ATTACK ; LV 7
    db 4, 3, WATER_GUN ; TM 12 TEM DUAS NO JOGO
    db 4, 4, TAIL_WHIP ; LV 1

    ; 17, EEVEE
    db 5, 1, TACKLE ; LV 1
    db 5, 2, TAIL_WHIP ; LV 1
    db 5, 3, SAND_ATTACK ; LV 8
    db 5, 4, GROWL ; LV 16

    db 0  ; Finaliza a lista

