;-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
;JOLTEON

	db RIVAL3, 1 ; Champion - 59, STARMIE , 59, ARCANINE, 58, ALAKAZAM, 58, EXEGGUTOR, 58, TAUROS, 60, JOLTEON, 0
    ; 59, STARMIE 
    db 1, 1, SURF ; HM 3
    db 1, 2, ICE_BEAM ; TM 13 SÓ TEM UM NO JOGO
    db 1, 3, THUNDER ; TM 25 SÓ TEM UM NO JOGO
    db 1, 4, RECOVER ; PRE LV 27

    ; 59, ARCANINE
    db 2, 1, FLAMETHROWER ; PRE LV 50
    db 2, 2, DRAGON_RAGE ; TM 23 PODE SER COMPRADO
    db 2, 3, HYPER_BEAM ; TM 15 PODE SER COMPRADO
    db 2, 4, DOUBLE_TEAM ; TM 32 PODE SER COMPRADO

    ; 58, ALAKAZAM
    db 3, 1, PSYCHIC_M; LV 38
    db 3, 2, PSYWAVE ; TM 46 SÓ TEM UM NO JOGO
    db 3, 3, RECOVER ; PRE LV 31
    db 3, 4, THUNDER_WAVE ; TM 45 SÓ TEM UM NO JOGO

    ; 58, EXEGGUTOR
    db 4, 1, PSYCHIC_M; TM 29 SÓ TEM UM NO JOGO
    db 4, 2, MEGA_DRAIN ;TM 21 SÓ TEM UM NO JOGO
    db 4, 3, HYPER_BEAM ; TM 15 PODE SER COMPRADO
    db 4, 4, SLEEP_POWDER ; PRE LV 48

    ; 58, TAUROS
    db 5, 1, BODY_SLAM ; TM 8 SÓ TEM UM NO JOGO
    db 5, 2, HYPER_BEAM ; TM 15 PODE SER COMPRADO
    db 5, 3, EARTHQUAKE ; TM 26 SÓ TEM UM NO JOGO
    db 5, 4, BLIZZARD ; TM 14 SÓ TEM UM NO JOGO

    ; 60, JOLTEON
    db 6, 1, THUNDERBOLT ; TM 24 SÓ TEM UM NO JOGO
    db 6, 2, DOUBLE_KICK ; LV 30
    db 6, 3, THUNDER_WAVE ; LV 42
    db 6, 4, DOUBLE_TEAM ;TM 32 PODE SER COMPRADO

    db 0  ; Finaliza a lista

;-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
;FLAREON

	db RIVAL3, 2 ; Champion - 59, RAICHU, 59, STARMIE , 58, ALAKAZAM, 58, EXEGGUTOR, 58, TAUROS, 60, FLAREON, 0
    ; 59, RAICHU
    db 1, 1, THUNDERBOLT ; TM 24 SÓ TEM UM NO JOGO
    db 1, 2, SEISMIC_TOSS ; TM 19 SÓ TEM UM NO JOGO
    db 1, 3, THUNDER_WAVE ; LV 8
    db 1, 4, DOUBLE_TEAM ; TM 32

    ; 59, STARMIE 
    db 2, 1, SURF ; HM 3
    db 2, 2, ICE_BEAM ; TM 13 SÓ TEM UM NO JOGO
    db 2, 3, THUNDER ; TM 25 SÓ TEM UM NO JOGO
    db 2, 4, RECOVER ; PRE LV 27

    ; 58, ALAKAZAM
    db 3, 1, PSYCHIC_M; LV 38
    db 3, 2, PSYWAVE ; TM 46 SÓ TEM UM NO JOGO
    db 3, 3, RECOVER ; PRE LV 31
    db 3, 4, THUNDER_WAVE ; TM 45 SÓ TEM UM NO JOGO

    ; 58, EXEGGUTOR
    db 4, 1, PSYCHIC_M; TM 29 SÓ TEM UM NO JOGO
    db 4, 2, MEGA_DRAIN ;TM 21 SÓ TEM UM NO JOGO
    db 4, 3, HYPER_BEAM ; TM 15 PODE SER COMPRADO
    db 4, 4, SLEEP_POWDER ; PRE LV 48

    ; 58, TAUROS
    db 5, 1, BODY_SLAM ; TM 8 SÓ TEM UM NO JOGO
    db 5, 2, HYPER_BEAM ; TM 15 PODE SER COMPRADO
    db 5, 3, EARTHQUAKE ; TM 26 SÓ TEM UM NO JOGO
    db 5, 4, BLIZZARD ; TM 14 SÓ TEM UM NO JOGO

    ; 60, FLAREON
    db 6, 1, FLAMETHROWER ; LV 52
    db 6, 2, DOUBLE_EDGE ; TM 10 SÓ TEM UM NO JOGO
    db 6, 3, HYPER_BEAM ; TM 15 PODE SER COMPRADO
    db 6, 4, SAND_ATTACK ; PRE LV 8

    db 0  ; Finaliza a lista

;-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
;VAPOREON

	db RIVAL3, 3 ; Champion - 59, ARCANINE, 59, RAICHU, 58, ALAKAZAM, 58, EXEGGUTOR, 58, TAUROS, 60, VAPOREON, 0
    ; 59, ARCANINE
    db 1, 1, FLAMETHROWER ; PRE LV 50
    db 1, 2, DRAGON_RAGE ; TM 23 PODE SER COMPRADO
    db 1, 3, HYPER_BEAM ; TM 15 PODE SER COMPRADO
    db 1, 4, DOUBLE_TEAM ; TM 32 PODE SER COMPRADO

    ; 59, RAICHU
    db 2, 1, THUNDERBOLT ; TM 24 SÓ TEM UM NO JOGO
    db 2, 2, SEISMIC_TOSS ; TM 19 SÓ TEM UM NO JOGO
    db 2, 3, THUNDER_WAVE ; LV 8
    db 2, 4, DOUBLE_TEAM ; TM 32

    ; 58, ALAKAZAM
    db 3, 1, PSYCHIC_M; LV 38
    db 3, 2, PSYWAVE ; TM 46 SÓ TEM UM NO JOGO
    db 3, 3, RECOVER ; PRE LV 31
    db 3, 4, THUNDER_WAVE ; TM 45 SÓ TEM UM NO JOGO

    ; 58, EXEGGUTOR
    db 4, 1, PSYCHIC_M; TM 29 SÓ TEM UM NO JOGO
    db 4, 2, MEGA_DRAIN ;TM 21 SÓ TEM UM NO JOGO
    db 4, 3, HYPER_BEAM ; TM 15 PODE SER COMPRADO
    db 4, 4, SLEEP_POWDER ; PRE LV 48

    ; 58, TAUROS
    db 5, 1, BODY_SLAM ; TM 8 SÓ TEM UM NO JOGO
    db 5, 2, HYPER_BEAM ; TM 15 PODE SER COMPRADO
    db 5, 3, EARTHQUAKE ; TM 26 SÓ TEM UM NO JOGO
    db 5, 4, BLIZZARD ; TM 14 SÓ TEM UM NO JOGO

    ; 60, VAPOREON
    db 6, 1, SURF ; HM 3
    db 6, 2, ICE_BEAM ; TM 13
    db 6, 3, ACID_ARMOR ; LV 47
    db 6, 4, REST ; TM 44

    db 0  ; Finaliza a lista

	db -1 ; end
