;ELITE 4

	db LORELEI, 1 ; 55, CLOYSTER, 54, JYNX, 54, JYNX, 54, JYNX, 55, DEWGONG, 56, LAPRAS, 0

    ; 55, CLOYSTER 
    db 1, 1, BLIZZARD
    db 1, 2, SURF
    db 1, 3, DOUBLE_EDGE
    db 1, 4, EXPLOSION

    ; 54, JYNX 
    db 2, 1, BLIZZARD
    db 2, 2, PSYCHIC_M
    db 2, 3, LOVELY_KISS ; LV 1
    db 2, 4, SUBSTITUTE

    ; 54, JYNX 
    db 3, 1, BLIZZARD
    db 3, 2, PSYCHIC_M
    db 3, 3, COUNTER
    db 3, 4, LOVELY_KISS ; LV 1

    ; 54, JYNX 
    db 4, 1, ICE_BEAM
    db 4, 2, PSYCHIC_M
    db 4, 3, LOVELY_KISS ; LV 1
    db 4, 4, SUBSTITUTE

    ; 55, DEWGONG 
    db 5, 1, BLIZZARD
    db 5, 2, SURF
    db 5, 3, REST 
    db 5, 4, DOUBLE_TEAM

    ; 56, LAPRAS 
    db 6, 1, BLIZZARD
    db 6, 2, SURF
    db 6, 3, THUNDERBOLT
    db 6, 4, REST

    db 0  ; Finaliza a lista


	db BRUNO, 1 ; 56, HITMONLEE, 56, HITMONCHAN, 55, PRIMEAPE, 55, POLIWRATH, 55, POLIWRATH, 57, MACHAMP, 0

    ; 56, HITMONLEE 
    db 1, 1, HI_JUMP_KICK ; LV 48
    db 1, 2, BODY_SLAM
    db 1, 3, DOUBLE_TEAM
    db 1, 4, MEDITATE ; LV 1

    ; 56, HITMONCHAN 
    db 2, 1, SUBMISSION 
    db 2, 2, BODY_SLAM
    db 2, 3, AGILITY ; LV 1
    db 2, 4, DOUBLE_TEAM

    ; 55, PRIMEAPE 
    db 3, 1, SUBMISSION
    db 3, 2, KARATE_CHOP ; PRE LV 15
    db 3, 3, THUNDERBOLT
    db 3, 4, ROCK_SLIDE

    ; 55, POLIWRATH 
    db 4, 1, SURF
    db 4, 2, EARTHQUAKE
    db 4, 3, AMNESIA ; PRE LV 38
    db 4, 4, HYPNOSIS ; PRE LV 16

    ; 55, POLIWRATH 
    db 5, 1, SUBMISSION
    db 5, 2, SURF
    db 5, 3, AMNESIA ; PRE LV 38
    db 5, 4, HYPNOSIS ; PRE LV 16

    ; 57, MACHAMP 
    db 6, 1, SUBMISSION
    db 6, 2, EARTHQUAKE
    db 6, 3, HYPER_BEAM
    db 6, 4, ROCK_SLIDE

    db 0  ; Finaliza a lista


	db AGATHA, 1 ; 57, GASTLY, 56, HAUNTER, 56, HAUNTER, 56, HAUNTER, 56, HAUNTER, 58, GENGAR, 0

    ; 57, GASTLY 
    db 1, 1, PSYCHIC_M
    db 1, 2, MEGA_DRAIN
    db 1, 3, HYPNOSIS ; LV 27
    db 1, 4, CONFUSE_RAY ; LV 1

    ; 56, HAUNTER 
    db 2, 1, PSYCHIC_M
    db 2, 2, EXPLOSION
    db 2, 3, HYPNOSIS ; PRE LV 27
    db 2, 4, CONFUSE_RAY ; PRE LV 1

    ; 56, HAUNTER 
    db 3, 1, PSYCHIC_M
    db 3, 2, THUNDERBOLT
    db 3, 3, HYPNOSIS ; PRE LV 27
    db 3, 4, CONFUSE_RAY ; PRE LV 1

    ; 56, HAUNTER 
    db 4, 1, NIGHT_SHADE
    db 4, 2, HYPNOSIS ; PRE LV 27
    db 4, 3, CONFUSE_RAY ; PRE LV 1
    db 4, 4, SUBSTITUTE

    ; 56, HAUNTER 
    db 5, 1, MEGA_DRAIN
    db 5, 2, PSYCHIC_M
    db 5, 3, THUNDERBOLT
    db 5, 4, CONFUSE_RAY ; PRE LV 1

    ; 58, GENGAR 
    db 6, 1, NIGHT_SHADE
    db 6, 2, PSYCHIC_M
    db 6, 3, HYPNOSIS ; PRE LV 27
    db 6, 4, CONFUSE_RAY ; PRE LV 1

    db 0  ; Finaliza a lista


	db LANCE, 1 ; 58, DRATINI, 57, DRAGONAIR, 57, DRAGONAIR, 57, DRAGONAIR, 57, DRAGONAIR, 59, DRAGONITE, 0

    ; 58, DRATINI 
    db 1, 1, WRAP ; LV 1
    db 1, 2, BLIZZARD
    db 1, 3, AGILITY ; LV 20
    db 1, 4, THUNDER_WAVE

    ; 57, DRAGONAIR 
    db 2, 1, WRAP ; PRE LV 1
    db 2, 2, THUNDERBOLT
    db 2, 3, THUNDER_WAVE
    db 2, 4, AGILITY ; PRE LV 20

    ; 57, DRAGONAIR 
    db 3, 1, WRAP ; PRE LV 1
    db 3, 2, THUNDERBOLT
    db 3, 3, ICE_BEAM
    db 3, 4, THUNDER_WAVE

    ; 57, DRAGONAIR 
    db 4, 1, WRAP ; PRE LV 1
    db 4, 2, HYPER_BEAM
    db 4, 3, BLIZZARD
    db 4, 4, THUNDER_WAVE

    ; 57, DRAGONAIR 
    db 5, 1, HYPER_BEAM
    db 5, 2, BLIZZARD
    db 5, 3, THUNDERBOLT
    db 5, 4, THUNDER_WAVE

    ; 59, DRAGONITE 
    db 6, 1, DRAGON_RAGE
    db 6, 2, HYPER_BEAM
    db 6, 3, THUNDERBOLT
    db 6, 4, BLIZZARD

    db 0  ; Finaliza a lista

